---
- name: copy local ssh keys to new vm, user root
  hosts: all
  sudo: true
  vars:
    ssh_public_key_path: '~/.ssh/id_rsa.pub'
  tasks:
    - name: creating "authorized_key" in vm
      authorized_key: 
        key="{{lookup('file', '~/.ssh/id_rsa.pub')}}"
        user='root'
        manage_dir=yes
